# Generated by Django 4.2.7 on 2023-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_designation_groupmaster_modules_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('organization_description', models.CharField(max_length=1000)),
                ('organization_email', models.EmailField(max_length=100)),
                ('organization_phoneNo', models.IntegerField()),
                ('organization_website', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
